# frozen_string_literal: true

source "https://rubygems.org"

# Declare your gem's dependencies in decidim-ldap.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem "deface"

group :development, :test do
  gem "bootsnap"
  gem "byebug", platform: :mri
  gem "decidim", ">= 0.23"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "ladle"
  gem "pry-byebug"
  # gem 'pry-coolline'
  gem "letter_opener_web", "~> 1.3"
  gem "listen"
  gem "pry-rails"
  gem "rubocop", require: false
  gem "spring-commands-rspec"
  gem "webmock"
end
