# frozen_string_literal: true

source 'https://rubygems.org'

ruby RUBY_VERSION

# This is the original line, but it doesn't work
# gem "decidim", path: "../.."
gem 'decidim', '~> 0.9.3'
gem 'decidim-admin', '~> 0.9.3'

# Uncomment the following line if you want to use decidim-assemblies plugin
# gem "decidim-assemblies", path: "../.."

gem 'bootsnap', require: false

gem 'puma', '~> 3.0'
gem 'uglifier'

gem 'faker'

group :development, :test do
  gem 'byebug', platform: :mri

  # gem "decidim-dev", path: "../.."
  gem 'decidim-dev', '~> 0.9.3'
end

group :development do
  gem 'letter_opener_web'
  gem 'listen', '~> 3.1.0'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console'
end
