source 'https://rubygems.org'

# Declare your gem's dependencies in decidim-ldap.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

group :test do
  gem 'decidim'
  gem 'decidim-age_action_authorization', path: '../decidim-age_action_authorization'
  gem 'pry-rails'
  gem 'decidim-ldap', path: '../decidim-ldap'
end
